### PR TITLE
add items images

### PR DESCRIPTION
**Pull request by Rodion15**

### CODE REVIEW

**Comment by linzera** [comment]
What about minifying those images using Pillow? So you can automate the process.

**Comment by Rodion15** [comment]
> А как насчет минимизации этих изображений с помощью Pillow? Таким образом, вы можете автоматизировать процесс.

I do not plan to minimize these images using Pillow, but if you know how to use it and want to utilize it, feel free to do so.

**Comment by mlg404** [comment]
Hi @Rodion15 !
A already the last changes (from last commits, renaming files). Update your origin!

And let me know when you finish so I can merge your PR!

**Comment by Rodion15** [comment]
@mlg404 It's ready now. I have already added the item.json file, which includes the name, image path, price, and weight.

**Pull request merged**
